HealthCareManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("userlogin.urls")),
    path("patient/", include("patient.urls")),
    path("doctor/", include("doctor.urls")),
    path("blockchain/", include("blockchainservice.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("profile/", views.profile, name='doctor_profile'),
    path("edit_profile/", views.edit_profile, name='edit_doctor_profile'),
    path("prescribe_medicine/<int:id>", views.prescribe_medicine, name='doctor_prescribe_medicine'),
]

patient/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("profile/", views.profile, name='patient_profile'),
    path("edit_profile/", views.edit_profile, name='edit_patient_profile'),
    path("report_upload/", views.add_report, name="patient_report_upload"),
    path("report_list/", views.report_list, name="patient_report_list"),
    path("report_view/<int:id>/", views.report_view, name="patient_report_view"),
    path("search_doctor/", views.search_doctor, name="patient_search_doctor"),
    path("chat/", views.chat, name="patient_doctor_chat"),
    path("doctorchat_add/<int:id>", views.doctor_add,name='patient_doctorchat_add'),
]

patient/models.py
from django.db import models
from userlogin.models import Patient
from django.contrib.auth import get_user_model
from django.db.models import Q

User = get_user_model()

# Create your models here.
class PatientReport(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE,related_name='reports')
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    report_file = models.FileField(upload_to='patient_reports/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)
    
    class Meta:
        ordering = ['-uploaded_at']



class ThreadManager(models.Manager):
    def by_user(self, **kwargs):
        user = kwargs.get('user')
        lookup = Q(first_person=user) | Q(second_person=user)
        qs = self.get_queryset().filter(lookup).distinct()
        return qs


class Thread(models.Model):
    first_person = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='thread_first_person')
    second_person = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,
                                     related_name='thread_second_person')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()
    class Meta:
        unique_together = ['first_person', 'second_person']


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.CASCADE, related_name='chatmessage_thread')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

userlogin/models.py
from django.contrib.auth.models import User
from django.db import models

class Specialist(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="specialists")

    def __str__(self):
        return self.name


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='patient')
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    email=models.EmailField()
    address = models.TextField()
    dob = models.DateField()
    gender = models.CharField(max_length=1, choices=[("m", "Male"),("f", "Female"), ("o", "Other")])
    height = models.DecimalField(decimal_places=2, max_digits=5)
    weight = models.DecimalField(decimal_places=2, max_digits=5)

    def __str__(self):
        return self.name


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='doctor')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    address = models.TextField()
    gender = models.CharField(max_length=1, choices=[("m", "Male"),("f", "Female"), ("o", "Other")])
    specialists = models.ManyToManyField(Specialist)

    def __str__(self):
        return self.name
    

class DeliveryBoy(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='deliveryboy')
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    vehicle_number = models.CharField(max_length=20)

    def __str__(self):
        return self.name

patient/forms.py
from django import forms
from userlogin.models import Patient
from .models import PatientReport
from django.core.validators import FileExtensionValidator

class PatientProfileForm(forms.ModelForm):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    phone_number = forms.CharField(
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    address = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control"}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', "type":"email"}))
    gender = forms.ChoiceField(
        choices=[('m', "Male"), ("f", "Female"), ("o", "Other")],
        widget=forms.RadioSelect
    )
    dob = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class':"form-control"}))
    height = forms.DecimalField(widget=forms.TextInput(attrs={"type":"number" ,'class':"form-control", "step":"0.1"}))
    weight = forms.DecimalField(widget=forms.TextInput(attrs={"type":"number" ,'class':"form-control", "step":"0.1"}))


    class Meta:
        model = Patient
        fields = ( 'name', 'phone_number', 'address', 'email', 'gender', 'dob', 'height', 'weight')

class PatientReportForm(forms.ModelForm):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )
    report_file = forms.FileField(widget=forms.FileInput(attrs={'type': 'file', 'class':"form-control"}),validators=[
            FileExtensionValidator(allowed_extensions=['pdf'])
        ])
    class Meta:
        model=PatientReport
        fields = ('name', 'description', 'report_file')

patient/views.py
from django.shortcuts import render, redirect, get_object_or_404,HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from .forms import PatientProfileForm, PatientReportForm
from datetime import datetime
from dateutil.parser import parse
from .models import PatientReport,Patient, Thread
from django.db.models.signals import post_save
from .signals import reportBlockHashCreate
from django.core.paginator import Paginator

from userlogin.models import Doctor, Specialist


post_save.connect(reportBlockHashCreate, PatientReport)
# Create your views here.
def calculate_age(date_of_birth):
    current_date = datetime.now()
    if isinstance(date_of_birth, str):
        date_of_birth = parse(date_of_birth, dayfirst=True)
    age = current_date.year - date_of_birth.year
    if current_date.month < date_of_birth.month or (current_date.month == date_of_birth.month and current_date.day < date_of_birth.day):
        age -= 1
    return age

def calculate_bmr(weight, height, age, gender):
    if gender == 'm' or gender=='o':
        bmr = 66 + (13.75 * weight) + (5 * height) - (6.75 * age)
    elif gender == 'f':
        bmr = 655 + (9.56 * weight) + (1.85 * height) - (4.68 * age)

    return bmr

def is_patient(user):
    return hasattr(user, 'patient')

@login_required(login_url='login')
@user_passes_test(is_patient, login_url='login')
def profile(request):
    patient = Patient.objects.get(user=request.user)
    patient.age=calculate_age(patient.dob)
    patient.bmi = round(patient.weight / ((patient.height/100) ** 2),2)
    patient.bmr=calculate_bmr(float(patient.weight), float(patient.height), int(patient.age), patient.gender)
    
    # Determine weight category based on BMI
    if patient.bmi < 18.5:
        patient.bmi_detail="Underweight"
    elif patient.bmi < 25:
        patient.bmi_detail="Normal Weight"
    elif patient.bmi < 30:
        patient.bmi_detail="Overweight"
    else:
        patient.bmi_detail="Obese"
    return render(request, "patient/profile.html", {"patient":patient, "disp":"profile"})

@login_required(login_url='login')
@user_passes_test(is_patient, login_url='login')
def edit_profile(request):
    user = get_object_or_404(Patient, user=request.user)

    if request.method == 'POST':
        form = PatientProfileForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect("patient_profile")
    else:
        form = PatientProfileForm(instance=user)

    return render(request, 'users/register.html', {"form": form, "register":"Edit Profile", "button_text":"Edit", "disp":"profile"})

@login_required(login_url='login')
@user_passes_test(is_patient, login_url='login')
def add_report(request):
    if request.method == 'POST':
        form = PatientReportForm(request.POST, request.FILES)
        if form.is_valid():
            report = form.save(commit=False)
            report.patient=request.user.patient
            report.save()
            
            return redirect('patient_report_list')
    else:
        form = PatientReportForm()
    return render(request, 'users/register.html', {'form': form,"register":"Report Upload","button_text":"Upload","disp":"report_upload"})


@login_required(login_url='login')
@user_passes_test(is_patient, login_url='login')
def report_list(request):
    reports = PatientReport.objects.filter(patient=request.user.patient)
    report_per_page = 25
    paginator = Paginator(reports, per_page=report_per_page)
    page_number = request.GET.get('page', 1)
    reports = paginator.get_page(page_number)
    context = {
        'reports': reports,
        'disp':'report_list',
        'check':paginator.count>report_per_page and reports,
    }
    return render(request, 'patient/report_list.html', context=context)

@login_required(login_url='login')
@user_passes_test(is_patient, login_url='login')
def report_view(request, id):
    report = get_object_or_404(PatientReport, patient=request.user.patient, id=id)
    return render(request, 'patient/report_view.html', {"report":report.report_file.url, "disp":"report_list"})


@login_required(login_url='login')
@user_passes_test(is_patient, login_url='login')
def search_doctor(request):
    specialist_ids = request.GET.getlist('specialists')
    
    if specialist_ids:
        doctors = Doctor.objects.filter(specialists__id__in=specialist_ids).distinct().order_by("id")
    else:
        doctors = Doctor.objects.all().order_by("id")

    report_per_page = 25
    paginator = Paginator(doctors, per_page=report_per_page)
    page_number = request.GET.get('page', 1)
    doctors = paginator.get_page(page_number)
    
    specialists = Specialist.objects.all()
    
    return render(request, 'patient/search_doctor.html', {'doctors': doctors, 'specialists': specialists, 
                                                          'check':paginator.count>report_per_page and doctors,
                                                          "selected_specialists":[int(i) for i in specialist_ids],
                                                          "disp":"search_doctor"})


def chat(request):
    threads = Thread.objects.by_user(user=request.user).prefetch_related('chatmessage_thread').order_by('timestamp')
    context = {
        'Threads': threads,
        'disp':"chat"
    }
    return render(request, "patient/messages.html", context)


@login_required(login_url='login')
@user_passes_test(is_patient, login_url='login')
def doctor_add(request, id):
    Thread.objects.create(first_person=request.user, second_person=Doctor.objects.get(id=id).user)
    return redirect("patient_doctor_chat")

templates/patient/messages.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

		

<link rel="stylesheet" href="{% static 'css/messages.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% if user.is_authenticated %}
{% comment %} <h1 style="text-align: end; padding-right: 10px">Logged in as : {{ user.username }}</h1> {% endcomment %}
<input type="hidden" id="logged-in-user" value="{{ user.id }}">
<input type="hidden" id="logged-in-user-name" value="{{ user.doctor }}">
{% endif %}
{% if Threads %}
<div class="container-fluid h-100">
    <div class="row justify-content-center h-100 ">
        <div class="col-md-4 col-xl-3 chat h-100 mt-4">
            <div class="card mb-sm-3 mb-md-0 contacts_card">
            <div class="card-body contacts_body">
                <ui class="contacts">
                    {% for thread in Threads %}
                        <li class="{% if forloop.first %}first-active{% endif %} contact-li" chat-id="chat_{{ thread.id }}" style="cursor: pointer">
                            <div class="d-flex bd-highlight">
                                {% if user.patient %}
                                <div class="img_cont">
                                    <img src="{% static 'images/doctor.avif' %}" class="rounded-circle user_img">
                                </div>
                                {% else %}
                                <div class="img_cont">
                                    <img src="{% static 'images/patient.png' %}" class="rounded-circle user_img">
                                </div>
                                {% endif %}
                                <div class="user_info">
                                    {% if thread.first_person == user %}
                                        <span>{{ thread.second_person.username }}</span>
                                    {% else %}
                                        <span>{{ thread.first_person.username }}</span>
                                    {% endif %}
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ui>
                <div class="card-footer"></div>
            </div>
        </div></div>
        <div class="col-md-8 col-xl-9 chat h-100 mt-4">
            <div class="card">
                {% for thread in Threads %}
                    <div class="messages-wrapper  {% if forloop.first %}hide is_active{% else %}hide{% endif %}" chat-id="chat_{{ thread.id }}" other-user-id="
                                {% if thread.first_person == user %}
                                    {{ thread.second_person.id }}
                                {% else %}
                                    {{ thread.first_person.id }}
                                {% endif %}
                            ">
                            <div class="left-right-container card-header">
                        <div class="msg_head">
                            
                            <div class="d-flex bd-highlight">
                                {% if user.doctor %}
                                <div class="img_cont">
                                    <img src="{% static 'images/patient.png' %}" class="rounded-circle user_img">
                                </div>
                                {% else %}
                                <div class="img_cont">
                                    <img src="{% static 'images/doctor.avif' %}" class="rounded-circle user_img">
                                </div>
                                {% endif %}
                                
                                <div class="user_info">
                                          {% if thread.first_person == user %}
                                            <span>Chat with {{ thread.second_person.username }}</span>
                                          {% else %}
                                            <span>Chat with {{ thread.first_person.username }}</span>
                                          {% endif %}
                                          
                                    
                                    <p>{{ thread.chatmessage_thread.all.count }} messages</p>
                                
                            </div>
                                
                            </div>
                        </div>
                        {% if user.doctor %}
                            <a class="btn btn-warning" href="{% url 'doctor_prescribe_medicine' thread.first_person.id %}">Prescribe Medicine</a>
                        {% endif %}
                        </div>

                        <div class="card-body msg_card_body">
                            {% for chat in thread.chatmessage_thread.all %}
                                {% if chat.user == user %}
                                    <div class="d-flex mb-4 replied">
                                        <div class="msg_cotainer_send">
                                            {{ chat.message }}
                                            <span class="msg_time_send">{{ chat.timestamp|date:"d D" }}, {{ chat.timestamp|time:"H:i" }}</span>
                                        </div>
                                        {% if user.doctor %}
                                    <div class="img_cont_msg">
                                        <img src="{% static 'images/doctor.avif' %}" class="rounded-circle user_img_msg">
                                    </div>
                                    {% else %}
                                    <div class="img_cont_msg">
                                        <img src="{% static 'images/patient.png' %}" class="rounded-circle user_img_msg">
                                    </div>
                                    {% endif %}
                                </div>
                                {% else %}
                                    <div class="d-flex mb-4 received">
                                        {% if user.doctor %}
                                    <div class="img_cont_msg">
                                        <img src="{% static 'images/patient.png' %}" class="rounded-circle user_img_msg">
                                    </div>
                                    {% else %}
                                    <div class="img_cont_msg">
                                        <img src="{% static 'images/doctor.avif' %}" class="rounded-circle user_img_msg">
                                    </div>
                                    {% endif %}
                                    <div class="msg_cotainer">
                                        {{ chat.message }}
                                        <span class="msg_time">{{ chat.timestamp|date:"d D" }}, {{ chat.timestamp|time:"H:i" }}</span>
                                    </div>
                                </div>
                                {% endif %}
                            {% endfor %}
                        </div>

                    </div>
                {% endfor %}
                <div class="card-footer">
                        <form id="send-message-form">
                            <div class="input-group">
                                <input type="text" name="" id="input-message" class="form-control type_msg" placeholder="Type your message...">
                                <div class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        <span class="input-group-text send_btn">
                                            <i class="fas fa-location-arrow"></i>
                                        </span>
                                    </button>

                                </div>
                        </div>
                        </form>
                    </div>
            </div>
        </div>
    </div>
</div>
{% else %}
No Chats Yet.
{% endif %}


<script src="{% static 'js/messages.js' %}"></script>
{% endblock %}

templates/patient/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section class="w-100 p-4" style="background-color: #eee; border-radius: .5rem .5rem 0 0;">



    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
            <h5 class="my-3">{{ patient.name }}</h5>
            <p class="text-muted mb-1">{% trans "Patient" %}</p>
            <p class="text-muted mb-4">{{patient.address}}</p>
            <div class="d-flex justify-content-center mb-2">
              <a type="button" class="btn btn-primary" href="{% url 'edit_patient_profile' %}">Edit</a>
            </div>
          </div>
        </div>
        {% comment %} <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fas fa-globe fa-lg text-warning"></i>
                <p class="mb-0">https://mdbootstrap.com</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                <p class="mb-0">mdbootstrap</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                <p class="mb-0">@mdbootstrap</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                <p class="mb-0">mdbootstrap</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                <p class="mb-0">mdbootstrap</p>
              </li>
            </ul>
          </div>
        </div> {% endcomment %}
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "Full Name"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.name}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "Email"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.email}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "Mobile"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.phone_number}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "User Name"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.user.username}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "Address"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.address}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "Gender"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.get_gender_display}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "Date of Birth"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.dob}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "Age"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.age}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "Height"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.height}} cm</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><b>{% trans "Weight"%}</b></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{patient.weight}} kg</p>
              </div>
            </div>
            
          </div>
        </div>

        
         <div class="row">
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4" style="text-align:center;"><b>{% trans "Body Mass Index (BMI)" %}</b></p>
                <div class="row">
                  <div class="col-sm-5">
                    <p class="mb-0"><b>{% trans "BMI Value : "%}</b></p>
                  </div>
                  <div class="col-sm-7">
                    <p class="text-muted mb-0">{{patient.bmi}}</p>
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-5">
                    <p class="mb-0"><b>{% trans "Weight Category : "%}</b></p>
                  </div>
                  <div class="col-sm-7">
                    <p class="text-muted mb-0">{{patient.bmi_detail}}</p>
                  </div>
                </div>
                
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4" style="text-align:center;"> <b>{% trans "Basic Metabolic Rate (BMR)" %}</b> </p>
                <div class="row">
                  <div class="col-sm-5">
                    <p class="mb-0"><b>{% trans "BMR Value : "%}</b></p>
                  </div>
                  <div class="col-sm-7">
                    <p class="text-muted mb-0">{{patient.bmr}}</p>
                  </div>
                </div>
                <hr>
                  <div >
                    <p class="text-muted mb-0">{% trans "This represents the minimum number of calories your body needs to function at rest." %}</p>
                  </div>
                
              </div>
            </div>
          </div>
        </div> 
      </div>
    </div>

  </section>


  {% endblock %}

templates/patient/report_view.html
<!DOCTYPE html>
<html>
<head>
    <title>PDF Viewer</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
        }
        
        #pdf-iframe {
            display: block;
            border: none;
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>
    <iframe id="pdf-iframe" src="{{report}}" allowfullscreen ></iframe>
</body>
</html>

templates/patient/search_doctor.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<link
      rel="stylesheet"
      href="{%static 'css/multi-select-tag.css'%}"
      type="text/css"
      media="screen"
    />
    <script src="{% static 'js/multi-select-tag.js' %}"></script>    
    

    
  
<div class="container">
    <div class="form-container">
    <form method="GET" >
    <select name="specialists" id="specialists" multiple>
      {% for specialist in specialists %}
        <option value="{{ specialist.id }}" {% if specialist.id in selected_specialists %} selected {% endif %}>{{ specialist.name }}</option>
      {% endfor %}
    </select>
    <br>
    <input type="submit" value="Search" class="form-control btn btn-primary">
  </form>
</div>
  
<br>
  {% if doctors %}
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>
                        {% trans "Name" %}
                    </th>
                    <th>
                        {% trans "Gender" %}
                    </th>
                    <th>
                        {% trans "Specialist" %}
                    </th>
                    <th>
                        {% trans "Address" %}
                    </th>
                    <th>{% trans "Chat" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for doctor in doctors %}
                <tr>
                    <td>{{ doctor.name }}</td>
                    <td>{{ doctor.get_gender_display }}</td>
                    <td><ul>
                        {% for specialist in doctor.specialists.all %}
                            <li>{{ specialist.name }}</li>
                        {% endfor %}
                        </ul></td>
                    
                    <td>
                        {{doctor.address}}
                        </td>

                    <td><a href="{% url 'patient_doctorchat_add' doctor.id %}" class="btn btn-primary"> Chat </a></td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% if check %}
            <div class="center">
            <div class="pagination1">
            {% if doctors.has_previous %}
                <a href="?page={{ doctors.previous_page_number }}">Previous</a>
            {% endif %}
            {% for page_number in doctors.paginator.page_range %}
                        <a
                            href="?page={{page_number}}"
                            class="{% if page_number == doctors.number %}active{% endif %}"
                        >
                            {{page_number}}
                        </a>
                {% endfor %}
                {% if doctors.has_next %}
                <a href="?page={{ doctors.next_page_number }}">Next</a>
            {% endif %}
            </div>
            </div>
            {% endif %}
    </div>
    {% else %}
    <p>{% trans "No Doctors found." %}</p>
    {% endif %}

    <script>
        new MultiSelectTag('specialists')
    </script>
  
  {% endblock %}
  
  